name: MasterDeployCI

on:
  push:
    branches:
      - main

jobs:
  firebase-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set-up Node
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: npm install
      - run: npm run build:noci
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@v2.0.0
        with:
          args: deploy --only hosting --project aditya-karnam-portfolio
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_DEPLOY_KEY }}